### ISSUE TITLE
[Defect] mlpack can no longer be built on m1 mac

### ISSUE THREAD

**Issue by suannchong** [ornlneutronimaging/mcpevent2hist#16]
**Describe the bug**
It was possible to build mlpack as dependency with conda on m1 mac before by specifying the arch with `CODNA_SUBDIR=osx-64`.
However, some recent change makes it impossible to find a matching package on `conda-forge`.

**To Reproduce**
Steps to reproduce the behavior: follow the setup env steps for mac in the instruction.

**Expected behavior**
Conda will report that incompatible package list with `mlpack` listed.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: MacOSX
 - Version: 13.4 

**Additional context**
N/A

**Comment by KedoKudo** [comment]
The `mlpack` incompability issue is caused by its dependency, `ensamllen`, which requires `openmp` that is not very well supported by Apple.
Instead of creating the environment with one config file, we need to do this in several steps in order to get it to work:

- Install a patched version of openmp lib via homebrew by `brew install libomp`.
  - If still running into issue with compiling openmp code, also install `llvm` with `brew install llvm`.
- Create the environment with environment file. Make sure mlpack is commented out as it will break the dependency search.
  - Since mlpack does not provide arm support, we need to set the conda environment to `osx-64` to run everything on Rosetta2, namely `CONDA_SUBDIR=osx-64 conda env create -f environment_mac.yml`
- Activate the environment and install `ensamllen` manually with `conda install -c conda-forge ensmallen`
- Once everything is installed, do `conda install -c conda-forge mlpack`.

This will get everything installed in the conda environment.
Also, this issue only affects m-series mac, so linux and intel-mac should not have similar issue.

**Comment by KedoKudo** [comment]
We are removing the dependency for mlpack for the moment so that we can ensure the application is native supported on apple silicon.

**Comment by bvacaliuc** [comment]
Apologies for submitting a PR for a closed issue, but I was working with my M1 mac laptop this weekend and the `next` branch did not have a working build.  Perhaps it helps in the future when needed to build components from source that do not have support in conda-forge.
